name: Deploy Laravel Admin to Hpanel

on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            PROJECT_DIR=/home/u723134020/domains/ahmakbar.com/api-test-app-d
            PUBLIC_LINK=/home/u723134020/domains/ahmakbar.com/public_html/api-test-app

            # Pakai Node/npm & Composer yang sudah ada di server
            export PATH="$HOME/bin/nodejs/bin:$PATH"
            node -v
            npm -v

            # Clone pertama kali
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              mkdir -p "$PROJECT_DIR"
              git clone https://github.com/ahmakbardev/api-test-app-d.git "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"
            git fetch origin develop
            git reset --hard origin/develop

            # Build assets (kalau ada)
            if [ -f package.json ]; then
              npm ci --legacy-peer-deps || npm install --legacy-peer-deps
              npm run prod || npm run build || true
            fi

            # Composer (panggil langsung dari path)
            $HOME/bin/composer install --no-dev --optimize-autoloader

            # Laravel housekeeping
            php artisan key:generate --force || true
            php artisan migrate --force || true
            php artisan storage:link || true
            php artisan route:clear
            php artisan config:cache
            php artisan optimize

            # ===== Buat symlink: api-test-app -> PROJECT_DIR/public =====
            # Pastikan parent ada
            mkdir -p "$(dirname "$PUBLIC_LINK")"
            # Kalau target sudah ada (folder/file/symlink), hapus dulu supaya tidak jadi "api-test-app/public"
            if [ -e "$PUBLIC_LINK" ] || [ -L "$PUBLIC_LINK" ]; then
              rm -rf "$PUBLIC_LINK"
            fi
            ln -s "$PROJECT_DIR/public" "$PUBLIC_LINK"
            # ============================================================
